# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Helen - A Programming Language
email: trolleybus.1329@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site about Helen programming language, created with Jekyll by hyst329.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hyst329.github.io/helen-site" # the base hostname & protocol for your site
twitter_username: trolley813
github_username:  hyst329

# Build settings
markdown: kramdown
